name: flex_movies
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  hive_flutter: ^1.1.0
  flutter_riverpod: ^1.0.4
  share_plus: ^4.4.0
  http: ^0.13.5
  cached_network_image: ^3.2.0
  iconly: ^1.0.1
  google_sign_in: ^5.1.0
  get: ^4.6.1
  iconsax: ^0.0.8
  youtube_player_flutter: ^8.1.2
  cached_video_player: ^2.0.3
  video_player: ^2.4.7
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.0.2
  path_provider: ^2.0.13
  # infinite_scroll_pagination: ^3.2.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-BlackItalic.ttf
        - asset: fonts/Raleway-Light.ttf
        - asset: fonts/Raleway-Medium.ttf
        - asset: fonts/Raleway-MediumItalic.ttf
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-SemiBold.ttf
        - asset: fonts/Raleway-SemiBoldItalic.ttf
       
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
