// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANSYZTXMCrf4fjDxfvCxXM3FxrBJiHU-g',
    appId: '1:1038404999035:web:f6c353b818d6d1ca754fde',
    messagingSenderId: '1038404999035',
    projectId: 'flex-movies-2ce4b',
    authDomain: 'flex-movies-2ce4b.firebaseapp.com',
    storageBucket: 'flex-movies-2ce4b.appspot.com',
    measurementId: 'G-2CS11P5BGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCTU3hTz_61fgB-3J3n_5lf1cfIr8bU4A',
    appId: '1:1038404999035:android:7cd8617ba52d7c12754fde',
    messagingSenderId: '1038404999035',
    projectId: 'flex-movies-2ce4b',
    storageBucket: 'flex-movies-2ce4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_THhYLYuCnUjxWCi3kKfbRrqnxssuJA8',
    appId: '1:1038404999035:ios:3deadbcee35d841c754fde',
    messagingSenderId: '1038404999035',
    projectId: 'flex-movies-2ce4b',
    storageBucket: 'flex-movies-2ce4b.appspot.com',
    iosClientId: '1038404999035-7dvlh9hqfrktea5vu240u8il717u47ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_THhYLYuCnUjxWCi3kKfbRrqnxssuJA8',
    appId: '1:1038404999035:ios:3deadbcee35d841c754fde',
    messagingSenderId: '1038404999035',
    projectId: 'flex-movies-2ce4b',
    storageBucket: 'flex-movies-2ce4b.appspot.com',
    iosClientId: '1038404999035-7dvlh9hqfrktea5vu240u8il717u47ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexMovies',
  );
}
